executor: slurm
default-resources:
  slurm_partition: "long,normal,big-mem,express"
  mem_mb_per_cpu: 8096
  mem_mb: None
  disk_mb: 1024000
  runtime: 600
#restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 12
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True