SAMPLES: config/samples.tsv
UNITS: config/units.tsv

OUTPUT:
    # REF: hg19  # TODO:
    RUN:
        QC: False
        QUANT: TRUE      # Trim | Align | Quant     
    LEVEL:
        - Gene
        - Transcript
    # TODO: DEseq2 
    # REF_CONDITION: Vh

REF:
    NAME: hg19
    FA: /groups/lackgrp/genomeAnnotations/hg19/hg19.fa
    GTF: /groups/lackgrp/genomeAnnotations/hg19/hg19.ncbiRefSeq.gtf
    TFA: /groups/lackgrp/genomeAnnotations/hg19/hg19.ncbiRefSeq.fa
    STAR_IDX: /groups/lackgrp/genomeAnnotations/hg19/hg19.ncbiRefSeq.star.idx
    CHROM_SIZES: /groups/lackgrp/genomeAnnotations/hg19/hg19.chrom.sizes

CUT_ADAPTERS: True
ADAPTER_FWD: CTGTCTCTTATA
ADAPTER_REV: CTGTCTCTTATA